### ISSUE TITLE
 heroku run rails db:migrateができない

### ISSUE THREAD

**Issue by reiayayougon** [reiayayougon/kosodate-mindcheck#3]
```
heroku run rails db:migrate
Running rails db:migrate on ⬢ kosodate-mind-check... up, run.6858 (Eco)
/usr/bin/env: 'ruby': No such file or directory
```
herokuがrubyファイル参照できていないです。
[![Image from Gyazo](https://i.gyazo.com/005ab4ad7b8d683255584effed7e6fa4.png)](https://gyazo.com/005ab4ad7b8d683255584effed7e6fa4)
https://www.amelt.net/imc/programming/rails/4788/
下記を参考にbin/ディレクトリ内を確認しました。
**bin/bundle**
```
#!/usr/bin/env ruby
# frozen_string_literal: true

#
# This file was generated by Bundler.
#
# The application 'bundle' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require "rubygems"

m = Module.new do
  module_function

  def invoked_as_script?
    File.expand_path($0) == File.expand_path(__FILE__)
  end

  def env_var_version
    ENV["BUNDLER_VERSION"]
  end
<省略>
```
**bin/rails
```
#!/usr/bin/env ruby
APP_PATH = File.expand_path("../config/application", __dir__)
require_relative "../config/boot"
require "rails/commands"

```

**bin/rake**
```
#!/usr/bin/env ruby
require_relative "../config/boot"
require "rake"
Rake.application.run

```
https://devcenter.heroku.com/ja/articles/wrong-version-of-ruby-or-rake-in-app
heroku configにPATHが設定されていないことを確認
```
heroku config
=== kosodate-mind-check Config Vars

RAILS_MASTER_KEY:.....

```

**Comment by Tsuchiya2** [comment]
[このチャンネルの使い方](https://chat.runteq.jp/runteq/pl/4zqoiwtq83nkmrmqdgmj9ywkfw) をご確認いただけますでしょうか？

```
- 質問内容・実現したいこと
- 現状発生している問題・エラーメッセージ
- どの処理までうまく動いているのか
- 該当のソースコード
- エラーから考えられる原因
- 試したこと
```

**Comment by kenchasonakai** [comment]
`heroku run rake db:migrate`を実行してみていただいてもよいでしょうか？
https://devcenter.heroku.com/ja/articles/getting-started-with-rails7#migrate-the-database

実行できなかった場合デプロイ時のログを確認して、assets:precompileやbundle installが正常に行われているかを確認してみるとなにかわかるかもしれませんね
↑build packの追加設定をミスしてrubyのbuild packが外れているとbundle installが行われずrailsのコマンドが実行出来ないことがあったような気がします
https://devcenter.heroku.com/ja/articles/using-multiple-buildpacks-for-an-app

**Comment by reiayayougon** [comment]
ありがとうございます！！！

設定がちゃんとなっていませんでした
```
heroku buildpacks
=== kosodate-mind-check Buildpack URL

heroku/nodejs
```

設定後
```
❯ heroku buildpacks                        
=== kosodate-mind-check Buildpack URLs

1. heroku/nodejs
2. heroku/ruby
```
