### ISSUE TITLE
変更したい内容

### ISSUE THREAD

**Issue by reiayayougon** [reiayayougon/kosodate-mindcheck#47]
### 修正したい箇所 ###
 **質問を表示しデータとして表示する流れのところです** 
[![Image from Gyazo](https://i.gyazo.com/245c217df1666603351c9aaa328b24c1.png)](https://gyazo.com/245c217df1666603351c9aaa328b24c1)
[![Image from Gyazo](https://i.gyazo.com/532466e81673dedaa2a9a5766084a60a.png)](https://gyazo.com/532466e81673dedaa2a9a5766084a60a)
[![Image from Gyazo](https://i.gyazo.com/bc1682f4d3c567464a831c5099501aaa.png)](https://gyazo.com/bc1682f4d3c567464a831c5099501aaa)

**変更後実装したい内容**
・質問として表示するのではなく投稿内容をランダムで表示
・投稿内容表示とともに(共感/共感しない)ボタン設定
・データとして共感が多かったユーザーを表示

## 変更したい理由 ##
・ユーザーにとって質問作成、投稿作成のそれぞれ作成する手間がある
・AIで質も出題も考えましたが機械的な質問内容なのでよりリアルな内容が欲しいのでやめました。ですが質問データがないと成り立たない。
・主旨は子育て仲間を作るアプリなので悩みのカテゴリをデータとして出すよりも仲間を作成できるよな後押しの方がいい

## 変更するメリット ##
・ユーザの作成手間が減る
・共感数が多いユーザーを見つけうことで絡みやすくなる

 ## 変更スクジュール ##
来週火曜日までにはできるようします。

**Comment by Tsuchiya2** [comment]
施策としては試してみる価値はあるかと思うので進めていただいて大丈夫です！

**Comment by reiayayougon** [comment]
ありがとうござます！
